### ISSUE TITLE
archive.extracted does not set excutable bits on NDK files during unzip

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#538]
This *should* be fixed in 2015.5.4/2015.8.0:
https://github.com/saltstack/salt/issues/23822

**Comment by aneeshusa** [comment]
I have not yet investigated, but note that Salt 2016.11 has apparently overhauled `archive.extracted` significantly: https://docs.saltstack.com/en/latest/topics/releases/2016.11.0.html#improved-archive-extraction-support

**Comment by aneeshusa** [comment]
Looking at [the docs for `archive.extracted` in 2016.11](https://docs.saltstack.com/en/2016.11/ref/states/all/salt.states.archive.html#salt.states.archive.extracted), it appears this is due to [an upstream Python bug](https://bugs.python.org/issue15795) in the `zipfile` module. This has been worked around by default in 2016.11; however, there appears to be no way to cause `archive.extracted` to fall back to the native `unzip` binary in 2016.3, so in the meantime we should go back to a combination of `file.managed` and `cmd.run`.

**Comment by aneeshusa** [comment]
In #639, I backported a fixed version of the `archive.extracted` module which includes a fix for this, and #641 tracks adding a test for this. Closing.
