### ISSUE TITLE
Mac builder updates

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#674]
Few items here:
 - [x] Pave the 3 unnamed, PROD1, and dev mac builders with macOS 10.10.5
 - [x] Provision the various builders as `servo-mac*` machines
 - [x] Bring servo-mac1 back online
 - [x] Update all the names of the mac builders https://github.com/servo/saltfs/blob/master/buildbot/master/files/config/master.cfg#L13
 - [x] Deploy ^^ to `servo-master` and restart buildbot
 - [x] Turn off servo-macpro1

@aneeshusa Are you done with your testing on servo-mac1?

cc @edunham

**Comment by aneeshusa** [comment]
It's currently finals week, I don't see myself using servo-mac1 anymore, feel free to pave :)
Any reason we'll no longer be using servo-macpro1?

We may need to update the [Buildbot config](https://github.com/servo/saltfs/blob/0536712bb93324f02a4d8332d00de3565a3caa32/buildbot/master/files/config/master.cfg#L13) so Buildbot knows about the new builders.
Also, @metajack filed #650 recently, so there may be some bumps while highstating.

**Comment by larsbergstrom** [comment]
@edunham Added the rest of the steps to push this through

**Comment by edunham** [comment]
None of the versions of xcode and command line tools in the app store were compatible with 10.10.5, and macstadium started all the new ones out at 10.10.0, so I got to spend a lot of today poking at GUI installers over a slow VNC connection. 

Mac8 has a nasty habit of setting its locale to Croatian in new accounts when they're created. I manually set it back to en-us for administrator and Servo, but just be aware it may do this if we recreate the Servo account. 

https://github.com/saltstack/salt/issues/34658 was keeping them from Salting, as noted in Jack's ticket,  because they couldn't retrieve the FailedLoginAttempts. We don't care about thoes in the slightest, so I have done a thing I know is bad practices as a stopgap and patched the Salt on each mac to shut up about it:

```
def _get_account_policy_data_value(name, key):
    '''
    Return the value for a key in the accountPolicy section of the user's plist
    file. For use by this module only

    :param str name: The username
    :param str key: The accountPolicy key

    :return: the value contained within the key
    :rtype: str

    :raises: CommandExecutionError on user not found or any other unknown error
    '''
    cmd = 'dscl . -readpl /Users/{0} accountPolicyData {1}'.format(name, key)
    try:
        ret = salt.utils.mac_utils.execute_return_result(cmd)
    except CommandExecutionError as exc:
        if 'eDSUnknownNodeName' in exc.strerror:
            raise CommandExecutionError('User not found: {0}'.format(name))
        ret = "" #TODO FIXME THIS IS AWFUL
        #raise CommandExecutionError('Unknown error: {0}'.format(exc.strerror))

    return ret
```

Current state is that 2, 6 and 7 have the patch and are highstating happily. 5 and 8 are supposed to have everything installed correctly but they aren't pinging from Salt so I need to VNC back in and troubleshoot. 9 is 2/3 of the way through initial setup (I started on it later than the others because Macstadium was delayed paving it, as I'd initially typo'd the IP) and needs: 

- [ ] install brew and git and pip
- [ ] download salt files
- [ ] Add the following to the com.saltstack.salt.minion.plist file just after the Label section
- [ ] coreaudiod / mdworker commands

from https://github.com/servo/servo/wiki/SaltStack-Administration and then it should be good to go (I skipped ahead on user account creation). 

The only hitch at the moment is that none of macs 5-9 have 1280x960 available as a resolution. Allegedly there's a key you can press to pick an arbitrary resolution but I couldn't get it to do that through VNC. I've set them all to 1600x900, which was the closest available resolution, for the time being.

**Comment by edunham** [comment]
5 is patched and back up. Turns out it had lost the salt master's IP from its hosts file.

**Comment by edunham** [comment]
8 had the same issue, and is now also patched and highstated. I tentatively blame the fact that I ran part of the system updates after manually adding Salt to the hosts file for its disappearance, whereas on 6 and 7 the updates showed up earlier so I happened to run them sooner in the process.

**Comment by edunham** [comment]
"deploy" turns out to mean "buildbot reconfig" rather than just highstate at the moment. 

macs 5-8 are now in Buildbot's rotation.

I have verified that 5-7 are logged in as Tom Servo, and when I checked on 8 it had yet another update so it's installing that at the moment.

**Comment by edunham** [comment]
Ok we're all like 
![image](https://cloud.githubusercontent.com/assets/812892/26475667/f4efbce4-416d-11e7-83c5-df106a5b4149.png) now. Macs 9 and 1 are back in; macpro1 is out.

http://build.servo.org/buildslaves

I *think* we should be good to spin down the pro, but let's leave it for a couple days so we can swap it back in if something goes horribly and unexpectedly wrong with the new builders as they do their first few builds.

**Comment by larsbergstrom** [comment]
Awesome - this is all super! BTW, IIRC macstadium asked that we do all shutdown requests via explicit support tickets rather than the UI so that the billing, etc. don't get messed up.

**Comment by edunham** [comment]
It's shut down, and I emailed the list with the update.

**Comment by aneeshusa** [comment]
I've deleted the `servo-macpro1` minion key from the Salt master.
