### ISSUE TITLE
Certificate for dl.servo.org is expired

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#994]

**Comment by jdm** [comment]
Same cert as download.servo.org.

**Comment by jdm** [comment]
certbot appears to only be set up to renew the build.servo.org script for reasons that are unclear to me. The renew script is https://github.com/servo/saltfs/blob/90036502c8fac2291fba372b3309bafef605f5b2/nginx/renew.sh.

**Comment by jdm** [comment]
Oh, download.servo.org is run through cloudflare, not nginx.

**Comment by jdm** [comment]
Ok, there's an amazon SSL cert in US-east 1 that is marked as ineligible for auto renewal which is being used for dl.servo.org.

**Comment by Darkspirit** [comment]
* download.servo.org and dl.servo.org are two SAN entries of the same Amazon Cloudfront TLS Certificate. https://www.ssllabs.com/ssltest/analyze.html?d=download.servo.org&s=99.84.224.55&hideResults=on&latest
* Guide about managed renewal: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cnames-and-https-rotate-certificates.html
* Please enable HTTP/2 in "Supported HTTP Versions".
* Please also set Security Policy (Minimum TLS version) to "TLSv1.2_2018". 
  * https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValues-security-policy
  * https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/secure-connections-supported-viewer-protocols-ciphers.html#secure-connections-supported-ciphers
  * (Cloudflare config was fixed by [bug 1482947](https://bugzilla.mozilla.org/show_bug.cgi?id=1482947) and [bug 1482941](https://bugzilla.mozilla.org/show_bug.cgi?id=1482941) in the past.
https://www.ssllabs.com/ssltest/analyze.html?d=servo.org&s=2606%3A4700%3A30%3A0%3A0%3A0%3A681f%3A4ae3&hideResults=on 
https://www.hardenize.com/report/servo.org/1575999752#summary )

**Comment by jdm** [comment]
The newly issued certificate is pending DNS ownership validation, so I haven't switched s3 to use it yet.

**Comment by jdm** [comment]
Fixed. The new certificate issued is now eligible for automatic renewal, so this shouldn't happen again.

**Comment by jdm** [comment]
I updated the minimum TLS version to the Cloudfront-recommended TLSv1.1_2016 and enabled HTTP/2 in supported HTTP versions.
